""" added complete address model

Revision ID: 0d6c340c9094
Revises: b53639a3b47b
Create Date: 2026-07-30 15:40:48.945176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d6c340c9094'
down_revision = 'b53639a3b47b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('house_number', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('street', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('area', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('district', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('pincode', sa.String(length=10), nullable=False))
        batch_op.drop_column('address_line')

    with op.batch_alter_table('coupons', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_coupons_code'), ['code'])

    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_user_profiles_user_id'), ['user_id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_users_email'), ['email'])
        batch_op.create_unique_constraint(batch_op.f('uq_users_google_id'), ['google_id'])

    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_vendors_email'), ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_vendors_email'), type_='unique')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_users_google_id'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_users_email'), type_='unique')

    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_profiles_user_id'), type_='unique')

    with op.batch_alter_table('coupons', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_coupons_code'), type_='unique')

    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address_line', sa.TEXT(), nullable=False))
        batch_op.drop_column('pincode')
        batch_op.drop_column('state')
        batch_op.drop_column('district')
        batch_op.drop_column('city')
        batch_op.drop_column('area')
        batch_op.drop_column('street')
        batch_op.drop_column('house_number')

    # ### end Alembic commands ###
