""" added tracking in Order

Revision ID: 2a06e757eeed
Revises: 9c3793b70bfd
Create Date: 2026-07-31 13:22:14.808928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a06e757eeed'
down_revision = '9c3793b70bfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tracking_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('carrier_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('tracking_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('tracking_url')
        batch_op.drop_column('carrier_name')
        batch_op.drop_column('tracking_number')

    # ### end Alembic commands ###
