"""added the discounted amount on the payment page

Revision ID: 320d8ff10b1e
Revises: 63a17ed96b9f
Create Date: 2026-07-30 09:41:36.628537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '320d8ff10b1e'
down_revision = '63a17ed96b9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subtotal_amount', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('subtotal_amount')

    # ### end Alembic commands ###
