""" added sales column in the admin panel

Revision ID: 3b959ed51357
Revises: 7ecbf65debd9
Create Date: 2026-08-06 17:08:08.455350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b959ed51357'
down_revision = '7ecbf65debd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_paid', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('paid_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('paid_by', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_column('paid_by')
        batch_op.drop_column('paid_at')
        batch_op.drop_column('is_paid')

    # ### end Alembic commands ###
