"""add vendor payout details and profile

Revision ID: 7ecbf65debd9
Revises: 08d1636cd684
Create Date: 2026-08-06 16:35:29.814274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ecbf65debd9'
down_revision = '08d1636cd684'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bank_account_holder', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('bank_account_number', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('bank_ifsc', sa.String(length=11), nullable=True))
        batch_op.add_column(sa.Column('bank_name', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('upi_id', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.drop_column('upi_id')
        batch_op.drop_column('bank_name')
        batch_op.drop_column('bank_ifsc')
        batch_op.drop_column('bank_account_number')
        batch_op.drop_column('bank_account_holder')

    # ### end Alembic commands ###
